bases/urls.py
from django.urls import path
from .views import Home
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_view.LoginView.as_view(template_name="bases/login.html"), name="login"),
    path('logout/', auth_view.LogoutView.as_view(), name="logout"),  # Eliminamos template_name aquí
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew

urlpatterns = [
   path('categorias/', CategoriaView.as_view(), name='categoria_list'),
   path('categorias/new', CategoriaNew.as_view(), name='categoria_new')
]

bases/models.py
from django.db import models
from django.contrib.auth.models import User


# A continuacion crearemos un modelo que va a ser heredado por todos los modelos del proyecto
class ClaseModelo(models.Model):
   estado = models.BooleanField(default=True)
   fecha_creacion = models.DateTimeField(auto_now_add=True)
   fecha_modificacion = models.DateTimeField(auto_now=True)
   user_creacion = models.ForeignKey(User,on_delete=models.CASCADE)
   user_modificacion = models.IntegerField(blank=True, null=True)

   class Meta:
      abstract = True # Con esto Django ya no va a tomar en cuenta a la hora de crear una migracion
      

inv/models.py
from django.db import models

from bases.models import ClaseModelo

class CatgoriaModel(ClaseModelo):
   descripcion = models.CharField(max_length=100, help_text='Descripcion', unique=True)

   def __str__(self) -> str:
      return f"{self.descripcion}"
   
   # Ahora si queremos que se guarde en mayuscula debemos hacerlo desde el modelo
   def save(self):
      self.descripcion = self.descripcion.upper()
      # Otra opcion con una sintaxis mas clara es usar
      # super().save()
      super(CatgoriaModel, self).save()

   class Meta:
      verbose_name_plural = "Categorias"
      db_table = "categorias"

inv/forms.py
from django import forms
from .models import CatgoriaModel

# Para crear un formulario empezamos usando una clase

class CategoriaForm(forms.ModelForm):
   class Meta:
      model = CatgoriaModel
      fields = ['descripcion', 'estado']
      labels = {'descripcion': 'Descripcion de categoria',
                 'estado': 'Estado'}
      widget = {'descripcion': forms.TextInput}

   def __init__(self, *args, **kwargs):
      super().__init__(*args,**kwargs)
      for field in iter(self.fields):
         self.fields[field].widget.attrs.update({
            'class': 'form-control'
         })

bases/views.py
# views.py
from django.shortcuts import render
from django.views import generic
# Este mixin va actuar como un midleware el cual exigira que este logeando antes de que pueda ver la vista
from django.contrib.auth.mixins import LoginRequiredMixin
class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    # Si no esta registrado mi usario le dire que se vaya al ..
    login_url='bases:login'

inv/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

# Ahora vamos a importar el formulario que creamos
from .models import CatgoriaModel
from .forms import CategoriaForm


# Recuerda que usamos el ListView para que muestra las tablas
class CategoriaView(LoginRequiredMixin, generic.ListView):
   model= CatgoriaModel
   template_name = "inv/categoria_list.html"

   # Recuerda que por defecto Django pone el nombre de obj al context
   context_object_name = "obj"
   login_url = "bases:login"


class CategoriaNew(LoginRequiredMixin, generic.CreateView):
   model=CatgoriaModel
   template_name="inv/categoria_form.html"
   context_object_name = "obj"
   form_class=CategoriaForm
   success_url=reverse_lazy("inv:categoria_list")
   login_url = "bases:login"

   # Cuando la data sea valida se guardara en la bd
   def form_valid(self, form):
      form.instance.user_creacion = self.request.user
      return super().form_valid(form)

bases/templates/bases/home.html
<!--Pongo base porque me refiero a mi carpeta template principal-->
{% extends 'base/base.html' %}

bases/templates/bases/login.html
{% extends 'base/base.html' %}
{% block sidebar %}
{% endblock sidebar %} 
{% block top_bar %} 
{% endblock top_bar %}
{% block page_content %} 
{% endblock page_content %} 
{% block footer %} 
{% endblock footer %} 
{% block login %}

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                </div>
                <small class="text-danger">
                  
                  {% if form.errors %}
                    {% for field in form %}
                      {% if field.errors %}
                        {% for error in field.errors  %}
                          {{error|escape}}
                        {% endfor %}
                      {% endif %}
                    {% endfor %}

                    {% if form.non_field_errors %}
                      {% for error in form.non_field_errors  %}
                          {{error|escape}}
                      {% endfor %}
                    {% endif %}
                  {% endif %}
                    
                </small>
                <form class="user" method="POST">
                <!--Recuerda que siempre se debe de imprimir o enviar una etiqueta de seguridad dentro de un formulario -->
                {% csrf_token %}
                  <div class="form-group">
                    <input
                      class="form-control form-control-user"
                      id="id_username"
                      name="username"
                      placeholder="Ingrese su usuario..."
                    />
                  </div>
                  <div class="form-group">
                    <input
                      type="password"
                      class="form-control form-control-user"
                      id="id_password"
                      name="password"
                      placeholder="Password"
                    />
                  </div>
                <button
                    type="submit"
                    class="btn btn-primary btn-user btn-block"
                  >
                    Acceder
                  </button>
                  <hr />
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="forgot-password.html"
                    >Forgot Password?</a
                  >
                </div>
                <div class="text-center">
                  <a class="small" href="register.html">Create an Account!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock login %}

inv/templates/inv/categoria_form.html
{% extends 'base/base.html' %}
{% block page_content %}

<form method="POST" class="form-inline">
   {% csrf_token %}  
<div class="col-xl-6 col-md-6 mb-6">
   <div class="card border-left-success shadow h-100 py-2">
       <div class="card-body">
           <div class="row no-gutters align-items-center">
               <div class="col mr-2">
                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                       Nueva Categoria
                   </div>
                   <div class="dropdown-divider"></div>
                   <div class="row">
                     <div class="col-10">
                        <div class="input-group">
                           <input type="text" name="descripcion" class="form-control" required id="id_descripcion" placeholder="Descripcion">
                        </div>
                     </div>
                     <div class="col-2">
                        <div class="form-group">
                           <label for="id_estado">Estado</label>
                           <input type="checkbox" name="estado" class="form-control" id="id_estado">
                        </div>
                     </div>
                     <!-- {{form.as_p}} -->
                   </div>
                   <div class="dropdown-divider"></div>
                   <div class="row">
                     <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                        <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                     </div>
                   </div>
               </div>
           </div>
       </div>
   </div>
</div>
</form>

{% endblock page_content %}
{% block js_page %}
{% endblock js_page %}
   

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
  <!-- Dropdown Card Example -->
  <div class="card shadow mb-4">
   <!-- Card Header - Dropdown -->
   <div
       class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
       <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
       <div class="dropdown no-arrow">
           <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
           </a>
           <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
               aria-labelledby="dropdownMenuLink">
               <div class="dropdown-header">Acciones</div>
               <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
               <a class="dropdown-item" href="#">Another action</a>
               <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="#">Something else here</a>
           </div>
       </div>
   </div>
   <!-- Card Body -->
   <div class="card-body">
      
      {% if not obj %}
         <div class="alert alert-info">
            No hay categorias
         </div>
      {% else %}
      <table class="table table-striped table-hover">
         <thead>
            <th>Id</th>
            <th>Descripcion</th>
            <th>Estado</th>
            <th>F. Creacion</th>
            <th>F. Modificacion</th>
            <th class="all">Acciones</th>
         </thead>
         <tbody>
            {% for item in obj  %}
               <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.descripcion }}</td>
                  <td>{{ item.estado }}</td>
                  <td>{{ item.fecha_creacion|date:"d/m/Y H:i:s" }}</td>
                  <td>{{ item.fecha_modificacion }}</td>
                  <td>
                     <a href="#" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                     <a href="#" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                  </td>
               </tr>               
            {% endfor %}
         </tbody>
      </table>
      {% endif %}
   </div>
</div>
{% endblock page_content %}
   

{% block js_page %}
{% endblock js_page %}